PVEHackathon/Models/Eventos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PVEHackathon.Models
{
    /// <summary>
    /// Convocatoria a la publicacion de ideas.
    /// </summary>
    public class Eventos
    {
        #region Atributos

        /// <summary>
        /// Nombre del Evento.
        /// </summary>
        public String nombre { get; set; }

        /// <summary>
        /// Descripción del Evento.
        /// </summary>
        public String descripcion { get; set; }

        /// <summary>
        /// Fecha en que inicia el Evento.
        /// </summary>
        public DateTime fechaInico { get; set; }

        /// <summary>
        /// Fecha en que acaba el evento. Es el límite para los usuarios publicar y responder al contentenido.
        /// </summary>
        public DateTime fechaClausura { get; set; }

        /// <summary>
        /// Lista de Ideas publicadas por los Estudiantes para este Evento específico.
        /// </summary>
        public List<Ideas> ideas { get; set; }

        /// <summary>
        /// Imagen principal del Evento.
        /// </summary>
        public String imagen { get; set; }
        #endregion


        #region Constructores

        public Eventos()
        {
            fechaInico = new DateTime();
            fechaClausura = new DateTime();
            ideas = new List<Ideas>();
            imagen =  "http://static.parastorage.com/services/wixapps/2.461.18/javascript/wixapps/apps/blog/images/no-image-icon.png";
        }

        #endregion


        #region Metodos
        public List<Ideas> getReporte()
        {
            List<Ideas> reporte = new List<Ideas>();
            reporte = ideas;

            reporte = reporte.OrderByDescending(x => x.likes.Count).ToList();

            return reporte;
        }
        #endregion
    }
}

PVEHackathon/Controllers/EventoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PVEHackathon.Models;

namespace PVEHackathon.Controllers
{
    public class EventoController : Controller
    {
        // GET: Evento
        public ActionResult EventosMain()
        {
            return View();
        }

        public ActionResult Index()

        {
            List<Eventos> eventos = new List<Eventos>();

            for (int i = 0; i < 5; i++)
            {
                var evento = new Eventos();
                evento.nombre = "User" + i;
                evento.descripcion = "Economía Nacional";
                evento.fechaInico = new DateTime(2016, 11, 30);
                evento.fechaClausura = new DateTime(2016, 11, 30);
                var idea = new Ideas();
                idea.agregarLike("20093278");
                idea.agregarLike("20093918");
                idea.agregarLike("20086787");
                idea.agregarLike("20096787");

                evento.ideas.Add(idea);

                eventos.Add(evento);
            }
            if (eventos == null)
            {
                return HttpNotFound();
            }
            // ideas.Count();
            ViewBag.Eventos = eventos;
            return View(eventos);
        }

    }
}

PVEHackathon/Controllers/IdeaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PVEHackathon.Models;

namespace PVEHackathon.Controllers
{
    public class IdeaController : Controller
    {
        // GET: Idea
        public ActionResult IdeasMain()
        {
            return View();
        }
        public ActionResult IdeaUnica()
        {
            return View();
        }

        public ActionResult Index()
        {
            List<Ideas> ideas = new List<Ideas>(); 
            
            for (int i = 0; i < 5; i++)
            {
                var idea = new Ideas();
                idea.autor = "User" + i;
                idea.problema = "Problema" + i;
                idea.titulo = "Titulo" + i;
                idea.solucion = "Solucion" + i;
                ideas.Add(idea);
            }
            if (ideas == null)
            {
                return HttpNotFound();
            }
           // ideas.Count();
            ViewBag.Ideas = ideas;
            return View(ideas);
        }

    }
}

PVEHackathon/Views/Evento/EventosMain.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = "Eventos";
}

<h2>Lista de eventos</h2>


@*<div class="list-group">
     
     @Html.ActionLink("deded", "IdeasMain", "Idea", null, new { @class = "list-group-item" })

</div>*@

<table class="table table-striped table-hover ">
    <thead>
        <tr>
            <th>Titulo</th>
            <th>Descripcion</th>
            
        </tr>
    </thead>
    <tbody> 
        <tr>
            @*<td ondblclick="@Html.("Index")"> Nombre</td>*@
            <td>@Html.ActionLink("Nombre", "Index", "Evento")</td>
            @*<td>@Html.Action("Index")</td>*@
          
            <td>Column content</td>
        </tr>
    </tbody>
</table> 

PVEHackathon/Views/Evento/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eventos</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<table class="table">
    <tr>
        <th>
            Nombre
        </th>
        <th>
            descripcion
        </th>
        <th>
            fechaInico
        </th>
        <th>
            fechaClausura
        </th>
        <th>
            ideas
        </th>
        <th>
            imagen
        </th>
        <th></th>
    </tr>

    @{
        int i = 0;
        foreach (var item in Model)
        {

            <tr>
                <td>
                    @ViewBag.Eventos[@i].nombre
                </td>
                <td>
                    @ViewBag.Eventos[@i].descripcion
                </td>
                <td>
                    @ViewBag.Eventos[@i].fechaInico
                </td>
                <td>
                    @ViewBag.Eventos[@i].fechaClausura
                </td>
                <td>
                    
                    @Html.ActionLink("ViewBag.Eventos[@i].idea","IdeaUnica","Idea")
                </td>
                <td>
                    <img src="ViewBag.Eventos[@i].imagen" alt="Alternate Text" />
                    
                </td>

            </tr>
            i++;
        }
    }

</table>